#!/bin/bash

x=`cat * 2> /dev/null | grep "^[a-z]" | sed -e 's/)/);/g'`
y=`find . -maxdepth 1 -type f -name "*.c"`

if [ "$y" == "" ]
then
    echo -e "\e[33mNo c files found in the current directory.\e[0m"
else
    echo -e "$x"
fi
